# The URL the site will be built for
base_url = "https://chill-sam.github.io"

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "tags"},
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
page_template = "page.html"
accent_color = "red"
background_color = "dark"
